closedverse/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

#from closedverse_main import urls
from closedverse.settings import STATIC_URL

# determine static root for admin app
#admin_root = admin.__file__.replace('__init__.py', 'static/admin')
# Set internal server error handler
handler500 = 'closedverse_main.views.server_err'
urlpatterns = [
    path('admin/', admin.site.urls),
    # edit - the below snippet and admin_root variable are only for if you don't want to use whitenoise
    # translation: i made all of this before realizing whitenoise could serve it lmao

    # serve static for admin, in production? since admin is the only app now
    # accomodations might be needed for other apps (e.g silk?)
    # also the slice is meant to normalize e.g static_url being '/s/' to just 's/', etc. (is this necessary? prob not)
    #re_path(r'^'+STATIC_URL[1:]+'admin/(?P<path>.*)$', serve, {'document_root': admin_root}),

    # URLs for Closedverse
    path('', include('closedverse_main.urls'))
]

closedverse_main/urls.py
from django.conf.urls import url, re_path
from django.views.static import serve
#from django.conf.urls.static import static
#from django.shortcuts import redirect

from . import views
from django.conf import settings

username = r'(?P<username>[A-Za-z0-9-\'-._ ]+)'
community = r'(?P<community>[0-9]+)'
post = r'(?P<post>[0-9]+)'
comment = r'(?P<comment>[0-9]+)'
uuidr = r'[0-9a-f\-]'

app_name = 'main'

urlpatterns = [
	# Root
	url(r'^^$|^communities$|^index.*$$', views.community_list, name='community-list'),
	# Accounts
	url(r'login/$', views.login_page, name='login'),
	url(r'signup/$', views.signup_page, name='signup'),
	url(r'reset/$', views.forgot_passwd, name='forgot-passwd'),
	url(r'logout/$', views.logout_page, name='logout'),
	# User pages
	url(r'users/'+ username +'/follow$', views.user_follow, name='user-follow'),
	url(r'users/'+ username +'/unfollow$', views.user_unfollow, name='user-unfollow'),
	url(r'users/'+ username +'$', views.user_view, name='user-view'),
	url(r'users/'+ username +'/posts$', views.user_posts, name='user-posts'),
	url(r'users/'+ username +'/yeahs$', views.user_yeahs, name='user-yeahs'),
	url(r'users/'+ username +'/comments$', views.user_comments, name='user-comments'),
	url(r'users/'+ username +'/following$', views.user_following, name='user-following'),
	url(r'users/'+ username +'/followers$', views.user_followers, name='user-followers'),
	url(r'users/'+ username +'/friends$', views.user_friends, name='user-friends'),
	# User page friends
	url(r'users/'+ username +'/friend_new$', views.user_friendrequest_create, name='user-fr-create'),
	url(r'users/'+ username +'/friend_accept$', views.user_friendrequest_accept, name='user-fr-accept'),
	url(r'users/'+ username +'/friend_reject$', views.user_friendrequest_reject, name='user-fr-reject'),
	url(r'users/'+ username +'/friend_cancel$', views.user_friendrequest_cancel, name='user-fr-cancel'),
	url(r'users/'+ username +'/friend_delete$', views.user_friendrequest_delete, name='user-fr-delete'),
	url(r'users/'+ username +'/tools/set$', views.user_tools_set, name='user-tools-set'),
	url(r'users/'+ username +'/tools$', views.user_tools, name='user-tools'),
	url(r'users/'+ username +'/tools/meta$', views.user_tools_meta, name='user-tools-meta'),
	url(r'users/'+ username +'/tools/warn$', views.user_tools_warnings, name='user-tools-warnings'),
	url(r'users/'+ username +'/tools/ban$', views.user_tools_bans, name='user-tools-bans'),
	url(r'users/'+ username +'/block$', views.user_addblock, name='user-addblock'),
	url(r'users/'+ username +'/block_rm$', views.user_rmblock, name='user-rmblock'),
	url(r'my_blacklist$', views.user_blocklist, name='block-list'),
	# Communities
	url(r'communities.search$', views.community_search, name='community-search'),
	url(r'communities/'+ community +'$', views.community_view, name='community-view'),
	url(r'communities/favorites$', views.community_favorites, name='community-favorites'),
	url(r'communities/categories/(?P<category>[a-z]+)$', views.community_all, name='community-viewall'),
	url(r'communities/(?P<tag>[a-z]+)$', views.special_community_tag, name='special-community-tag'),
	url(r'communities/'+ community +'/favorite$', views.community_favorite_create, name='community-favorite-add'),
	url(r'communities/'+ community +'/favorite_rm$', views.community_favorite_rm, name='community-favorite-rm'),
	url(r'communities/'+ community +'/posts$', views.post_create, name='post-create'),
	url(r'communities/'+ community +'/tools$', views.community_tools, name='community-tools'),
	url(r'communities/'+ community +'/tools/set$', views.community_tools_set, name='community-tools-set'),
	url(r'c/create$', views.community_create, name='community-create'),
	url(r'c/create/do$', views.community_create_action, name='community-create-action'),
	# Posts and comments
	# Some of these NAMES (not patterns) are hardcoded into models.py
	url(r'posts/'+ post +'$', views.post_view, name='post-view'),
	url(r'posts/'+ post +'/yeah$', views.post_add_yeah, name='post-add-yeah'),
	url(r'posts/'+ post +'/yeahu$', views.post_delete_yeah, name='post-delete-yeah'),
	url(r'posts/'+ post +'/comments$', views.post_comments, name='post-comments'),
	url(r'posts/'+ post +'/lock-comments$', views.lock_the_comments, name='lock-the-comments'),
	url(r'posts/'+ post +'/change$', views.post_change, name='post-change'),
	url(r'posts/'+ post +'/profile$', views.post_setprofile, name='post-set-profile'),
	url(r'posts/'+ post +'/profile_rm', views.post_unsetprofile, name='post-unset-profile'),
	url(r'posts/'+ post +'\.rm$', views.post_rm, name='post-rm'),
	url(r'comments/'+ comment +'$', views.comment_view, name='comment-view'),
	url(r'comments/'+ comment +'/yeah$', views.comment_add_yeah, name='comment-add-yeah'),
	url(r'comments/'+ comment +'/yeahu$', views.comment_delete_yeah, name='comment-delete-yeah'),
	url(r'comments/'+ comment +'/change$', views.comment_change, name='comment-change'),
	url(r'comments/'+ comment +'/rm$', views.comment_rm, name='comment-rm'),
	# Post-meta: polls
	url(r'poll/(?P<poll>[0-9]+)/vote$', views.poll_vote, name='poll-vote'),
	url(r'poll/(?P<poll>[0-9]+)/unvote$', views.poll_unvote, name='poll-unvote'),

	# Notifications
	url(r'alive$', views.check_notifications, name='check-notifications'),
	url(r'notifications/?$', views.notifications, name='notifications'),
	url(r'notifications/friend_requests/?$', views.friend_requests, name='friend-requests'),
	url(r'notifications/(?P<notification>'+ uuidr +'+)\.rm$', views.notification_delete, name='notification-delete'),

	# User meta + messages
	url(r'activity/?$', views.activity_feed, name='activity'),
	url(r'users.search$', views.user_search, name='user-search'),
	url(r'pref$', views.prefs, name='prefs'),
	url(r'settings/profile$', views.profile_settings, name='profile-settings'),
	url(r'messages/?$', views.messages, name='messages'),
	url(r'messages/(?P<message>[0-9]+)/rm$', views.message_rm, name='message-delete'),
	url(r'messages/'+ username +'$', views.messages_view, name='messages-view'),
	url(r'messages/'+ username +'/read$', views.messages_read, name='messages-read'),

	# Help/configuration
	url(r'lights$', views.set_lighting, name='set-lighting'),
	url(r'complaints$', views.help_complaint, name='complaints'),
	url(r'invite$', views.invites, name='invites'),
	url(r'invite/create$', views.create_invite, name='create-invite'), 
	url(r'mydata$', views.my_data, name='my-data'),
	url(r'changepassword$', views.change_password, name='change-password'),
	url(r'server$', views.server_stat, name='server-stat'),
	url(r'help/rules/?$', views.help_rules, name='help-rules'),
	url(r'help/faq/?$', views.help_faq, name='help-faq'),
	url(r'help/legal/?$', views.help_legal, name='help-legal'),
	url(r'help/contact/?$', views.help_contact, name='help-contact'),
	url(r'help/login/?$', views.help_login, name='help-login'),
	url(r'help/whatads/?$', views.whatads, name='what-ads'),
	url(r'why/?$', views.help_why, name='help-why'),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# serve static and media i think???? mighTTT???????
urlpatterns += [re_path(r'^i/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

closedverse_main/templates/closedverse_main/man/manage_bans.html
{% extends "closedverse_main/layout.html" %}
{% block main-body %}{% load closedverse_user %}{% load closedverse_tags %}
{% user_sidebar request user profile 9 False %}
<div class="main-column"><div class="post-list-outline">
<h2 class="label">Ban {{ user.username }}</h2>
<form class="setting-form" method="post" action={% url "main:user-tools-bans" user.username %}>
		{% if not banned %}
		<li class="setting">
        <p class="settings-label">Why this user is banned:</p>
		{{ form.reason }}
		<p class="settings-label">Ban this user for:</p>
		{{ form.expiry_date }}
		<p class='note'>{{ user.username }} will be banned from {{ brand_name }} until the time runs out.</p>
		<p class="settings-label">Purge this user?</p>
		{{ form.purge }}
		<p class='note'>Should we purge {{ user.username }}? All comments and posts will be removed.</p>
		</li>
		{% csrf_token %}
		<div class="form-buttons">
			<input type="submit" class="button apply-button" value="Ban {{ user.username }}">
		</div>
		{% else %}
		<p class="label">This user is banned already.</p>
		    <p>The ban will expire on: {{ active_ban.expiry_date }}</p>
			<p>Time remaining: {{ active_ban.expiry_date|timeuntil }}</p>
			
			<li class="setting">
			<p class="settings-label">Edit Reasoning:</p>
			{{ form.reason }}
			<p class="settings-label">Change Expiry date:</p>
			{{ form.expiry_date }}
			<p class="settings-label">Active:</p>
			{{ form.active }}
			<p class='note'>Uncheck this to unban {{ user.username }}.</p>
			</li>
			{% csrf_token %}
			<div class="form-buttons">
				<input type="submit" class="button apply-button" value="Edit ban for {{ user.username }}">
			</div>
		{% endif %}
</form></div></div>
{% endblock %}

closedverse_main/templates/closedverse_main/man/manage_warnings.html
{% extends "closedverse_main/layout.html" %}
{% block main-body %}{% load closedverse_user %}{% load closedverse_tags %}
{% user_sidebar request user profile 8 False %}
<div class="main-column"><div class="post-list-outline">
<h2 class="label">Send a warning to {{ user.username }}</h2>
<form class="setting-form" method="post" action={% url "main:user-tools-warnings" user.username %}>
		<li class="setting">
        <p class="settings-label">Reasoning:</p>
		{{ form.reason }}
		<p class='note'>Warnings will show as notifications. {{ user.username }} will not be able to post, comment, or message another user until this notification is seen. {{ user.username }} will not see who sent this warning. Please add important details and context when specifying a reason.</p>
		</li>
		<div class="user-data">
		{% if unread_warnings %}<li>
		<p class='setting'>Warnings notifications that have not been read yet:<p>
		<table style="width:100%">
				<tr>
					<th>Time</th>
					<th>Reasoning</th>
				</tr>
				{% for Notifications in unread_warnings %}
				<tr>
					<td>{{ Notifications.created }}</td>
					<td>{{ Notifications.context_warning.reason }}</td>
				</tr>
				{% endfor %}
			</table>{% endif %}
			</li>{% if all_warnings %}
		<p class='setting'>Warning history:<p>
		<table style="width:100%">
				<tr>
					<th>Time</th>
					<th>Issued by</th>
					<th>Reasoning</th>
				</tr>
				{% for Warning in all_warnings %}
				<tr>
					<td>{{ Warning.created }}</td>
					<td>{{ Warning.by }}</td>
					<td>{{ Warning.reason }}</td>
				</tr>
				{% endfor %}
			</table>{% endif %}
			</div>
		{% csrf_token %}
		<div class="form-buttons">
			<input type="submit" class="button apply-button" value="Send warning to {{ user.username }}">
		</div>
</form></div></div>
{% endblock %}

closedverse_main/templates/closedverse_main/man/usertools.html
{% extends "closedverse_main/layout.html" %}
{% block main-body %}{% load closedverse_user %}{% load closedverse_tags %}
{% user_sidebar request user profile 7 False %}
<div class="main-column"><div class="post-list-outline">
<h2 class="label">Change settings for {{ user.username }}</h2>
<form class="setting-form" method="post" action={% url "main:user-tools-set" user.username %}>
		{% for field in user_form %}
			<li class='setting'>
				{% if field.field.widget.input_type == 'checkbox' %}
					<p>&nbsp;</p>
					{{ field }}{{ field.label_tag }}
				{% elif field.field.widget.input_type == 'number' %}
				<p class='settings-label'>{{ field.label_tag }}</p>
				{{ field }}
				{% elif field.field.widget.input_type == 'select' %}
				<p class='settings-label'>{{ field.label_tag }}</p>
				<div class="select-content">
                    <div class="select-button">
				        {{ field }}
				    </div>
				</div>
				{% else %}
					<p class='settings-label'>{{ field.label_tag }}</p>
					<div class="center-input">{{ field }}</div>
				{% endif %}
				<p class='note'>{{ field.help_text }}</p>
				</li>
		{% endfor %}

		{% for field in profile_form %}
			<li class='setting'>
				{% if field.field.widget.input_type == 'checkbox' %}
					<p>&nbsp;</p>
					{{ field }}{{ field.label_tag }}
				{% elif field.field.widget.input_type == 'number' %}
				<p class='settings-label'>{{ field.label_tag }}</p>
				{{ field }}
				{% elif field.field.widget.input_type == 'select' %}
				<p class='settings-label'>{{ field.label_tag }}</p>
				<div class="select-content">
                    <div class="select-button">
				        {{ field }}
				    </div>
				</div>
				{% else %}
					<p class='settings-label'>{{ field.label_tag }}</p>
					<div class="center-input">{{ field }}</div>
				{% endif %}
				<p class='note'>{{ field.help_text }}</p>
				</li>
		{% endfor %}
			<li class="setting">
			<p class="settings-label">Purge content:</p>
			{% for field in purge_form %}
				{{ field }}{{ field.label_tag }}
				<p class='note'>{{ field.help_text }}</p>
			{% endfor %}
			</li>
		{% if accountmatch %}
			<h3>Account(s) found with the same IP address.</h3>
			<div class="user-data">
			<table style="width:100%">
				<tr>
					<th>Created</th>
					<th>Match</th>
				</tr>
				{% for accountmatch in accountmatch %}
				<tr>
					<td>{{ accountmatch.created }}</td>
					<td><a href={% url "main:user-view" accountmatch.username %}>{{ accountmatch.username }}</a></td>
				</tr>
				{% endfor %}
			</table>
			</div>
		{% endif %}
		{% csrf_token %}
		<div class="form-buttons">
			<input type="submit" class="black-button apply-button" value="Save">
		</div>
</form></div></div>
{% endblock %}

closedverse_main/templates/closedverse_main/man/usertoolsmeta.html
{% extends "closedverse_main/layout.html" %}
{% block main-body %}{% load closedverse_user %}{% load closedverse_tags %}
{% user_sidebar request user profile 10 False %}
<div id="help" class="main-column">
<div class="post-list-outline">
<h2 class="label">View info for {{ user.username }}</h2>
<div class="help-content">
			<p class="settings-label">Account metadata: Mods under level {{ min_lvl_metadata_perms }} can't see this.</p>
			<div class="user-data">
				<p>Like any other site, we collect small bits of information from accounts for security reasons.
			<h3>General account information:</h3>
				<p>IP address: <span>{% if user.addr %}{{ user.addr }}{% else %}Data missing{% endif %}
				<p>Signup IP address: <span>{% if user.signup_addr %}{{ user.signup_addr }}{% else %}Data missing{% endif %}</p>
				<p>Email: <span>{% if user.email %}{{ user.email }}{% else %}Data missing{% endif %}
				<p>Rank: <span>{% if user.is_staff %}Staff member.{% elif not user.level <= 0 %}Moderator. (Level {{ user.level }}){% else %}Regular user.{% endif %}
			</div>
			{% if accountmatch %}
			<h3>Account(s) found with the same IP address.</h3>
			<div class="user-data">
			<table style="width:100%">
				<tr>
					<th>Related account</th>
					<th>Created</th>
				</tr>
				{% for accountmatch in accountmatch %}
				<tr>
					<td><a href={% url "main:user-view" accountmatch.username %}>{{ accountmatch.username }}</a></td>
					<td>{{ accountmatch.created }}</td>
				</tr>
				{% endfor %}
			</table>
			</div>
			{% endif %}
			{% if log_attempt %}
			<h3>Account login history:</h3>
			<div class="user-data">
			<table style="width:100%">
				<tr>
					<th>Time</th>
					<th class="ip">IP</th>
					<th>User agent</th>
				</tr>
				{% for log_attempt in log_attempt %}
				<tr>
					<td>{{ log_attempt.created }}</td>
					<td class="ip">{{ log_attempt.addr }}</td>
					<td>{{ log_attempt.user_agent }}
				</tr>
				{% endfor %}
				</table>
			</div>
			{% else %}
			<p>Error: No login history to report, it was likely deleted.</p>
			{% endif %}
			<p class='red'>Do I need to state the obvious? Please don't share this, ever!</p>
</div></div></div></div>
{% endblock %}