closedverse/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

#from closedverse_main import urls
from closedverse.settings import STATIC_URL

# determine static root for admin app
#admin_root = admin.__file__.replace('__init__.py', 'static/admin')
# Set internal server error handler
handler500 = 'closedverse_main.views.server_err'
urlpatterns = [
    path('admin/', admin.site.urls),
    # edit - the below snippet and admin_root variable are only for if you don't want to use whitenoise
    # translation: i made all of this before realizing whitenoise could serve it lmao

    # serve static for admin, in production? since admin is the only app now
    # accomodations might be needed for other apps (e.g silk?)
    # also the slice is meant to normalize e.g static_url being '/s/' to just 's/', etc. (is this necessary? prob not)
    #re_path(r'^'+STATIC_URL[1:]+'admin/(?P<path>.*)$', serve, {'document_root': admin_root}),

    # URLs for Closedverse
    path('', include('closedverse_main.urls'))
]

closedverse_main/urls.py
from django.conf.urls import url, re_path
from django.views.static import serve
#from django.conf.urls.static import static
#from django.shortcuts import redirect

from . import views
from django.conf import settings

username = r'(?P<username>[A-Za-z0-9-\'-._ ]+)'
community = r'(?P<community>[0-9]+)'
post = r'(?P<post>[0-9]+)'
comment = r'(?P<comment>[0-9]+)'
uuidr = r'[0-9a-f\-]'

app_name = 'main'

urlpatterns = [
	# Root
	url(r'^^$|^communities$|^index.*$$', views.community_list, name='community-list'),
	# Accounts
	url(r'login/$', views.login_page, name='login'),
	url(r'signup/$', views.signup_page, name='signup'),
	url(r'reset/$', views.forgot_passwd, name='forgot-passwd'),
	url(r'logout/$', views.logout_page, name='logout'),
	# User pages
	url(r'users/'+ username +'/follow$', views.user_follow, name='user-follow'),
	url(r'users/'+ username +'/unfollow$', views.user_unfollow, name='user-unfollow'),
	url(r'users/'+ username +'$', views.user_view, name='user-view'),
	url(r'users/'+ username +'/posts$', views.user_posts, name='user-posts'),
	url(r'users/'+ username +'/yeahs$', views.user_yeahs, name='user-yeahs'),
	url(r'users/'+ username +'/comments$', views.user_comments, name='user-comments'),
	url(r'users/'+ username +'/following$', views.user_following, name='user-following'),
	url(r'users/'+ username +'/followers$', views.user_followers, name='user-followers'),
	url(r'users/'+ username +'/friends$', views.user_friends, name='user-friends'),
	# User page friends
	url(r'users/'+ username +'/friend_new$', views.user_friendrequest_create, name='user-fr-create'),
	url(r'users/'+ username +'/friend_accept$', views.user_friendrequest_accept, name='user-fr-accept'),
	url(r'users/'+ username +'/friend_reject$', views.user_friendrequest_reject, name='user-fr-reject'),
	url(r'users/'+ username +'/friend_cancel$', views.user_friendrequest_cancel, name='user-fr-cancel'),
	url(r'users/'+ username +'/friend_delete$', views.user_friendrequest_delete, name='user-fr-delete'),
	url(r'users/'+ username +'/tools/set$', views.user_tools_set, name='user-tools-set'),
	url(r'users/'+ username +'/tools$', views.user_tools, name='user-tools'),
	url(r'users/'+ username +'/tools/meta$', views.user_tools_meta, name='user-tools-meta'),
	url(r'users/'+ username +'/tools/warn$', views.user_tools_warnings, name='user-tools-warnings'),
	url(r'users/'+ username +'/tools/ban$', views.user_tools_bans, name='user-tools-bans'),
	url(r'users/'+ username +'/block$', views.user_addblock, name='user-addblock'),
	url(r'users/'+ username +'/block_rm$', views.user_rmblock, name='user-rmblock'),
	url(r'my_blacklist$', views.user_blocklist, name='block-list'),
	# Communities
	url(r'communities.search$', views.community_search, name='community-search'),
	url(r'communities/'+ community +'$', views.community_view, name='community-view'),
	url(r'communities/favorites$', views.community_favorites, name='community-favorites'),
	url(r'communities/categories/(?P<category>[a-z]+)$', views.community_all, name='community-viewall'),
	url(r'communities/(?P<tag>[a-z]+)$', views.special_community_tag, name='special-community-tag'),
	url(r'communities/'+ community +'/favorite$', views.community_favorite_create, name='community-favorite-add'),
	url(r'communities/'+ community +'/favorite_rm$', views.community_favorite_rm, name='community-favorite-rm'),
	url(r'communities/'+ community +'/posts$', views.post_create, name='post-create'),
	url(r'communities/'+ community +'/tools$', views.community_tools, name='community-tools'),
	url(r'communities/'+ community +'/tools/set$', views.community_tools_set, name='community-tools-set'),
	url(r'c/create$', views.community_create, name='community-create'),
	url(r'c/create/do$', views.community_create_action, name='community-create-action'),
	# Posts and comments
	# Some of these NAMES (not patterns) are hardcoded into models.py
	url(r'posts/'+ post +'$', views.post_view, name='post-view'),
	url(r'posts/'+ post +'/yeah$', views.post_add_yeah, name='post-add-yeah'),
	url(r'posts/'+ post +'/yeahu$', views.post_delete_yeah, name='post-delete-yeah'),
	url(r'posts/'+ post +'/comments$', views.post_comments, name='post-comments'),
	url(r'posts/'+ post +'/lock-comments$', views.lock_the_comments, name='lock-the-comments'),
	url(r'posts/'+ post +'/change$', views.post_change, name='post-change'),
	url(r'posts/'+ post +'/profile$', views.post_setprofile, name='post-set-profile'),
	url(r'posts/'+ post +'/profile_rm', views.post_unsetprofile, name='post-unset-profile'),
	url(r'posts/'+ post +'\.rm$', views.post_rm, name='post-rm'),
	url(r'comments/'+ comment +'$', views.comment_view, name='comment-view'),
	url(r'comments/'+ comment +'/yeah$', views.comment_add_yeah, name='comment-add-yeah'),
	url(r'comments/'+ comment +'/yeahu$', views.comment_delete_yeah, name='comment-delete-yeah'),
	url(r'comments/'+ comment +'/change$', views.comment_change, name='comment-change'),
	url(r'comments/'+ comment +'/rm$', views.comment_rm, name='comment-rm'),
	# Post-meta: polls
	url(r'poll/(?P<poll>[0-9]+)/vote$', views.poll_vote, name='poll-vote'),
	url(r'poll/(?P<poll>[0-9]+)/unvote$', views.poll_unvote, name='poll-unvote'),

	# Notifications
	url(r'alive$', views.check_notifications, name='check-notifications'),
	url(r'notifications/?$', views.notifications, name='notifications'),
	url(r'notifications/friend_requests/?$', views.friend_requests, name='friend-requests'),
	url(r'notifications/(?P<notification>'+ uuidr +'+)\.rm$', views.notification_delete, name='notification-delete'),

	# User meta + messages
	url(r'activity/?$', views.activity_feed, name='activity'),
	url(r'users.search$', views.user_search, name='user-search'),
	url(r'pref$', views.prefs, name='prefs'),
	url(r'settings/profile$', views.profile_settings, name='profile-settings'),
	url(r'messages/?$', views.messages, name='messages'),
	url(r'messages/(?P<message>[0-9]+)/rm$', views.message_rm, name='message-delete'),
	url(r'messages/'+ username +'$', views.messages_view, name='messages-view'),
	url(r'messages/'+ username +'/read$', views.messages_read, name='messages-read'),

	# Help/configuration
	url(r'lights$', views.set_lighting, name='set-lighting'),
	url(r'complaints$', views.help_complaint, name='complaints'),
	url(r'invite$', views.invites, name='invites'),
	url(r'invite/create$', views.create_invite, name='create-invite'), 
	url(r'mydata$', views.my_data, name='my-data'),
	url(r'changepassword$', views.change_password, name='change-password'),
	url(r'server$', views.server_stat, name='server-stat'),
	url(r'help/rules/?$', views.help_rules, name='help-rules'),
	url(r'help/faq/?$', views.help_faq, name='help-faq'),
	url(r'help/legal/?$', views.help_legal, name='help-legal'),
	url(r'help/contact/?$', views.help_contact, name='help-contact'),
	url(r'help/login/?$', views.help_login, name='help-login'),
	url(r'help/whatads/?$', views.whatads, name='what-ads'),
	url(r'why/?$', views.help_why, name='help-why'),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# serve static and media i think???? mighTTT???????
urlpatterns += [re_path(r'^i/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

closedverse_main/templates/closedverse_main/elements/block-modal.html
{% load closedverse_user %}
<div class="dialog none" data-modal-types="post-block">
	<div class="dialog-inner">
		<div class="window">
			<h1 class="window-title">{% if profile.is_blocked %}Unblock{% else %}Block{% endif %} {{ user.nickname }}</h1>
			<div class="window-body">
				{% user_sidebar_info user profile %}
				<form method="post" data-action="{% if profile.is_blocked %}{% url "main:user-rmblock" user.username %}{% else %}{% url "main:user-addblock" user.username %}{% endif %}">
					<p class="window-body-content">Really {% if profile.is_blocked %}un{% endif %}block this user?{% if not profile.is_blocked %} You won't be able to see each other's posts or profile.{% endif %}</p>
					<div class="form-buttons">
						<input type="button" class="olv-modal-close-button gray-button" value="No">
						<input type="submit" value="Yes" class="post-button black-button">
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

closedverse_main/templates/closedverse_main/elements/comment-form.html
{% load closedverse_community %}
<form id="reply-form" class="for-identified-user" method="post" action="{% url "main:post-comments" post.id %}">
  {% csrf_token %}
  	{% if not user.limit_remaining is False %}
		<div class="post-count-container">
			<span>Remaining posts for today</span>
			<span class="remaining-today-post-count">{{ user.limit_remaining }}</span>
		</div>
	{% endif %}

  {% feeling_selector %}

  	<div class="textarea-with-menu active-text">
	  <div class="textarea-container">
		  <textarea name="body" class="textarea-text textarea" maxlength="2200" placeholder="Add a comment here." data-required></textarea>
	  </div>
	    <div class="textarea-memo none">
			
		</div>
  {% memo_drawboard %}

  </div>
	  {% if user.has_freedom %}
  	  {% file_button %}
  	  <!-- hack to temporarily hide video input, for now... -->
			<style>div.file-button-container{display:none;}</style>
	  {% endif %}

  <div class="post-form-footer-options">
    <div class="post-form-footer-option-inner post-form-spoiler">
      <label class="spoiler-button symbol">
        <input type="checkbox" id="is_spoiler" name="is_spoiler" value="1">
        Spoilers
      </label>
    </div>
  </div>


  <div class="form-buttons">
    <input type="submit" class="black-button reply-button disabled" value="Send" data-url-id="{{ post.id }}" data-post-content-type="text" data-post-with-screenshot="nodata" disabled="">
  </div>
</form>

closedverse_main/templates/closedverse_main/elements/discordapp-spinner.html
<p>I'm loading it !</p>

closedverse_main/templates/closedverse_main/elements/empathy-content.html
{% load closedverse_tags %}<div id="empathy-content"{% if not yeahs %} class="none"{% endif %}>
{% if myself.is_authenticated %}<a href="{% url "main:user-view" myself.username %}" {% if not has_yeah %} style="display: none;"{% endif %} class="post-permalink-feeling-icon visitor{% if myself.get_class.0 %} official"><img src="{% user_class myself %}" class="official-tag">{% else %}">{% endif %}<img src="{% avatar myself %}" class="user-icon"></a>{% endif %}
{% for yeah in yeahs %}{% if not myself.is_authenticated or not yeah.by == myself %}
<a href="{% url "main:user-view" yeah.by.username %}" class="post-permalink-feeling-icon{% if yeah.by.get_class.0 %} official"><img src="{% user_class yeah.by %}" class="official-tag">{% else %}">{% endif %}<img src="{% avatar yeah.by yeah.feeling %}" class="user-icon"></a>
{% endif %}{% endfor %}
</div>

closedverse_main/templates/closedverse_main/elements/feeling-selector.html
<div class="feeling-selector js-feeling-selector test-feeling-selector"><label class="symbol feeling-button feeling-button-normal checked"><input type="radio" name="feeling_id" value="0"{% if val == 0 %} checked{% endif %}><span class="symbol-label">normal</span></label><label class="symbol feeling-button feeling-button-happy"><input type="radio" name="feeling_id" value="1"{% if val == 1 %} checked{% endif %}><span class="symbol-label">happy</span></label><label class="symbol feeling-button feeling-button-like"><input type="radio" name="feeling_id" value="2"{% if val == 2 %} checked{% endif %}><span class="symbol-label">like</span></label><label class="symbol feeling-button feeling-button-surprised"><input type="radio" name="feeling_id" value="3"{% if val == 3 %} checked{% endif %}><span class="symbol-label">surprised</span></label><label class="symbol feeling-button feeling-button-frustrated"><input type="radio" name="feeling_id" value="4"{% if val == 4 %} checked{% endif %}><span class="symbol-label">frustrated</span></label><label class="symbol feeling-button feeling-button-puzzled"><input type="radio" name="feeling_id" value="5"{% if val == 5 %} checked{% endif %}><span class="symbol-label">puzzled</span></label>
</div>

closedverse_main/templates/closedverse_main/elements/file-button.html
<label class="file-button-container">
  <span class="input-label">File <span id="image-dimensions">Images, videos and audio are supported.</span></span>
  <span class="button file-upload-button">Upload</span>
  <input type="file" style="display: none;" id="upload-file" name="file">
    <div id="upload-preview-container" class="screenshot-container still-image" style="display: none;">
      <img id="upload-preview">
      <!-- not functional currently
      	<video id="video-upload-preview"></video>
      -->
    </div>
</label>

closedverse_main/templates/closedverse_main/elements/memo-drawboard.html
    <div id="memo-drawboard-page" class="dialog none">
	<div class="dialog-inner">
	  <div class="window">
		<h1 class="window-title">Drawing</h1>
		<div class="window-body">
      <div class="memo-buttons">
      <button type="button" class="artwork-clear"></button>
      <button type="button" class="artwork-undo"></button>
      <button type="button" class="artwork-pencil small selected"></button>
      <button type="button" class="artwork-eraser small"></button>
      <button type="button" class="artwork-fill"></button>
      <input type="text" class="artwork-color">
      <button type="button" class="artwork-zoom"></button>
      </div>
      <div class="memo-canvas">
	  <canvas id="artwork-canvas" zoom="2"></canvas>
      <canvas id="artwork-canvas-undo"></canvas>
      <canvas id="artwork-canvas-redo"></canvas>
			<input type="hidden" name="painting" value="">
			</div>
			<div class="form-buttons">
				<input class="olv-modal-close-button black-button memo-finish-btn" type="button" value="Finish">
				<button type="button" class="artwork-lock none"></button>
			  </div>
		</div>
	  </div>
	</div>
</div>

closedverse_main/templates/closedverse_main/elements/message-list.html
{% load closedverse_user %}  <div class="list messages" data-next-page-url="{% if next %}?offset={{ next }}{% endif %}">
      
	  {% for post in messages %}
		{% message post %}
	 {% endfor %}

  </div>

closedverse_main/templates/closedverse_main/elements/p_username.html
<p class="user-name"><a {% if user.color %}style=color:{{ user.color }}{% endif %} href="{% url "main:user-view" user.username %}">{{ user.nickname }}</a><span class="user-id">{{ user.username }}</span></p>

closedverse_main/templates/closedverse_main/elements/post-comment.html
{% if not comment.is_rm %}{% load closedverse_tags %}<li id="comment-{{ comment.id }}" {% if comment.spoils and not comment.is_mine %}data-href-hidden{% else %}data-href{% endif %}="{% url "main:comment-view" comment.id %}" class="post {% if comment.owner_post %}my{% else %}other{% endif %}{% if comment.spoils and not comment.is_mine %} hidden{% endif %} trigger">
  {% user_icon_container comment.creator comment.feeling %}
  <div class="body">
    <div class="header">
      <p class="user-name"><a {% if comment.creator.color %}style=color:{{ comment.creator.color }}{% endif %} href="{% url "main:user-view" comment.creator.username %}">{{ comment.creator.nickname }}</a></p>
	  <p class="timestamp-container">
        <a class="timestamp" {% if comment.spoils and not comment.is_mine %}data-href-hidden{% else %}href{% endif %}="{% url "main:comment-view" comment.id %}">{% time comment.created %}</a>
		{% if comment.has_edit %}
			<span class="spoiler">· Edited</span>
		{% endif %}
        <span class="spoiler-status{% if comment.spoils %} spoiler{% endif %}"> · Spoilers</span>
      </p>
    </div>

    <div class="reply-content-text">{{ comment.body|linebreaksbr }}</div>
	{% if comment.file %}
	{% if comment.file_type == 1 %}<div class="screenshot-container still-image"><img src="{{ comment.file.url }}"></div>
	{% elif comment.file_type == 2 %}<div class="screenshot-container"><video controls src="{{ comment.file.url }}" style="max-width:100%;max-height: 450px;"></video></div>
	{% elif comment.file_type == 3 %}<div class="screenshot-container"><audio controls src="{{ comment.file.url }}"></audio></div>
	{% else %}<a>File attached</a>
	{% endif %}
	{% endif %}
	{% if comment.spoils and not comment.is_mine %}
		<div class="hidden-content"><p>This comment contains spoilers.</p>
      <button type="button" class="hidden-content-button">View Comment</button>
    </div>
	{% endif %}

    <div class="reply-meta">
		<button type="button" {% if not comment.can_yeah %}disabled{% endif %} class="symbol submit yeah-button
		  {% if comment.has_yeah %}empathy-added{% endif %}
		  " data-is-in-reply-list="1" data-feeling="" data-action="{% url "main:comment-add-yeah" comment.id %}" data-url-id="{{ comment.id }}"><span class="yeah-button-text">{% empathy_txt comment.feeling comment.has_yeah %}</span></button>
        <div class="empathy symbol"><span class="symbol-label">Yeahs</span><span class="empathy-count">{{ comment.number_yeahs }}</span></div>
    </div>
  </div>
</li>
{% endif %}

closedverse_main/templates/closedverse_main/elements/profile-post.html
{% load closedverse_tags %}<div {% if post.spoils and not post.is_mine %}data-href-hidden{% else %}data-href{% endif %}="{% url "main:post-view" post.id %}" class="post trigger{% if post.file_type == 1 and not for_announcements %} with-image{% endif %}{% if post.spoils and not post.is_mine %} hidden test-hidden{% endif %}" tabindex="0">
  
    <p class="community-container"><a {% if post.community.clickable %}href="{% url "main:community-view" post.community_id %}"{% endif %}><img src="{{ post.community.icon }}" class="community-icon">{{ post.community.name }}</a></p>

  <div {% if not for_announcements %}class="body"{% endif %}>
    <div class="post-content">
		  {% user_icon_container post.creator post.feeling %}
          
          <p class="user-name"><a {% if post.creator.color %}style=color:{{ post.creator.color }}{% endif %} href="{% url "main:user-view" post.creator.username %}">{{ post.creator.nickname }}</a></p>
          
            <p class="timestamp-container">
				{% if post.spoils %}
				<span class="spoiler">Spoilers</span>·
				{% endif %}
				{% if post.has_edit %}
				<span class="spoiler">Edited ({% time post.edited %})</span>·
				{% endif %}
              <a class="timestamp" {% if post.spoils and not post.is_mine %}data-href-hidden{% else %}href{% endif %}="{% url "main:post-view" post.id %}">{% time post.created %}</a>
            </p>
				{% if post.yt_vid and not post.file_type == 2 %}
					<a href="{% url "main:post-view" post.id %}" class="{% if not for_announcements %}screenshot-container {% else %}announcement-container {% endif %}video"><img height="48" src="https://i.ytimg.com/vi/{{ post.yt_vid }}/default.jpg"></a>
				{% endif %}
			{% if post.file %}
				{% if post.file_type == 1 %}
				<a href="{% url "main:post-view" post.id %}" class="{% if not for_announcements %}screenshot-container {% else %}announcement-container {% endif %}still-image"><img src="{{ post.file.url }}"></a>
				{% elif post.file_type == 2 %}
				<div class="{% if not for_announcements %}screenshot-container {% else %}announcement-container {% endif %} video"><video src="{{ post.file.url }}" width="50" height="48"></video></div>
				{% else %}<a>File attached</a>
				{% endif %}
			{% endif %}
				{% if post.has_line_trun %}
				<p class="post-content-text">{{ post.body|truncatechars:100 }}</p>
				{% else %}
				<p class="post-content-text">{{ post.body|truncatechars:100|linebreaksbr }}</p>
			{% endif %}
			{% if post.spoils and not post.is_mine %}
			<div class="hidden-content"><p>This post contains spoilers.
                <button type="button" class="hidden-content-button">View Post</button>
          </p></div>
			{% endif %}
			{% if not for_announcements %}
        <div class="post-meta">
		  <button type="button"{% if not post.can_yeah %} disabled{% endif %} class="symbol submit yeah-button
		  {% if post.has_yeah %}empathy-added{% endif %}
		  " data-feeling="" data-action="{% url "main:post-add-yeah" post.id %}" data-community-id="{{ post.community.unique_id }}" data-url-id="{{ post.id }}"><span class="yeah-button-text">{% empathy_txt post.feeling post.has_yeah %}</span></button>
          {% if post.url %}
		  <a class="link-confirm symbol button" href="{{ post.url }}"></a>
		  {% endif %}
		  <div class="empathy symbol"><span class="symbol-label">Yeahs</span><span class="empathy-count">{{ post.number_yeahs }}</span></div>
          <div class="reply symbol"><span class="symbol-label">Comments</span><span class="reply-count">{{ post.number_comments }}</span></div>
        </div>
        {% endif %}

    </div>
  </div>
</div>

closedverse_main/templates/closedverse_main/elements/profile-user-list.html
{% load closedverse_user %}<div class="list follow-list">
  <ul class="list-content-with-icon-and-text arrow-list" id="friend-list-content" data-next-page-url="{% if next %}?offset={{ next }}{% endif %}">
  {% for user in users %}
  {% profile_user user request %}
  {% endfor %}
  </ul>
</div>

closedverse_main/templates/closedverse_main/elements/profile-user.html
{% load closedverse_tags %}<li class="trigger" data-href="{% url "main:user-view" user.username %}">
    {% user_icon_container user %}

{% if request.user.is_authenticated and not user.is_following %}
<div class="toggle-button">
    <button type="button" data-action="{% url "main:user-follow" user.username %}" class="follow-button button symbol relationship-button">Follow</button>
      <button type="button" class="button follow-done-button relationship-button symbol none" disabled="">Follow</button>
</div>
{% endif %}

  <div class="body">
    <p class="title">
      <span class="nick-name"><a {% if user.color %}style=color:{{ user.color }}{% endif %} href="{% url "main:user-view" user.username %}">{{ user.nickname }}</a></span>
      <span class="id-name">{{ user.username }}</span>
    </p>
    <p class="text">{{ user.profile.comment }}</p>

	  {% if user.profile.favorite.screenshot %}
      <div class="user-profile-memo-content">
        <img src="{{ user.profile.favorite.screenshot }}" class="user-profile-memo">
      </div>
	  {% endif %}
  </div>
</li>

closedverse_main/templates/closedverse_main/elements/u-post-list.html
{% load closedverse_tags %}{% load closedverse_user %}<div class="list post-list js-post-list" data-next-page-url="{% if next %}?offset={{ next }}{% if time %}&offset_time={{ time|urlencode }}{% endif %}{% endif %}">
{% if posts %}
{% for post in posts %}
{% user_post post type %}
{% endfor %}
{% else %}
{% if nf %}{% nocontent nf %}{% else %}{% nocontent "The posts couldn't be loaded." %}{% endif %}
{% endif %}
</div>