closedverse/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

#from closedverse_main import urls
from closedverse.settings import STATIC_URL

# determine static root for admin app
#admin_root = admin.__file__.replace('__init__.py', 'static/admin')
# Set internal server error handler
handler500 = 'closedverse_main.views.server_err'
urlpatterns = [
    path('admin/', admin.site.urls),
    # edit - the below snippet and admin_root variable are only for if you don't want to use whitenoise
    # translation: i made all of this before realizing whitenoise could serve it lmao

    # serve static for admin, in production? since admin is the only app now
    # accomodations might be needed for other apps (e.g silk?)
    # also the slice is meant to normalize e.g static_url being '/s/' to just 's/', etc. (is this necessary? prob not)
    #re_path(r'^'+STATIC_URL[1:]+'admin/(?P<path>.*)$', serve, {'document_root': admin_root}),

    # URLs for Closedverse
    path('', include('closedverse_main.urls'))
]

closedverse_main/urls.py
from django.conf.urls import url, re_path
from django.views.static import serve
#from django.conf.urls.static import static
#from django.shortcuts import redirect

from . import views
from django.conf import settings

username = r'(?P<username>[A-Za-z0-9-\'-._ ]+)'
community = r'(?P<community>[0-9]+)'
post = r'(?P<post>[0-9]+)'
comment = r'(?P<comment>[0-9]+)'
uuidr = r'[0-9a-f\-]'

app_name = 'main'

urlpatterns = [
	# Root
	url(r'^^$|^communities$|^index.*$$', views.community_list, name='community-list'),
	# Accounts
	url(r'login/$', views.login_page, name='login'),
	url(r'signup/$', views.signup_page, name='signup'),
	url(r'reset/$', views.forgot_passwd, name='forgot-passwd'),
	url(r'logout/$', views.logout_page, name='logout'),
	# User pages
	url(r'users/'+ username +'/follow$', views.user_follow, name='user-follow'),
	url(r'users/'+ username +'/unfollow$', views.user_unfollow, name='user-unfollow'),
	url(r'users/'+ username +'$', views.user_view, name='user-view'),
	url(r'users/'+ username +'/posts$', views.user_posts, name='user-posts'),
	url(r'users/'+ username +'/yeahs$', views.user_yeahs, name='user-yeahs'),
	url(r'users/'+ username +'/comments$', views.user_comments, name='user-comments'),
	url(r'users/'+ username +'/following$', views.user_following, name='user-following'),
	url(r'users/'+ username +'/followers$', views.user_followers, name='user-followers'),
	url(r'users/'+ username +'/friends$', views.user_friends, name='user-friends'),
	# User page friends
	url(r'users/'+ username +'/friend_new$', views.user_friendrequest_create, name='user-fr-create'),
	url(r'users/'+ username +'/friend_accept$', views.user_friendrequest_accept, name='user-fr-accept'),
	url(r'users/'+ username +'/friend_reject$', views.user_friendrequest_reject, name='user-fr-reject'),
	url(r'users/'+ username +'/friend_cancel$', views.user_friendrequest_cancel, name='user-fr-cancel'),
	url(r'users/'+ username +'/friend_delete$', views.user_friendrequest_delete, name='user-fr-delete'),
	url(r'users/'+ username +'/tools/set$', views.user_tools_set, name='user-tools-set'),
	url(r'users/'+ username +'/tools$', views.user_tools, name='user-tools'),
	url(r'users/'+ username +'/tools/meta$', views.user_tools_meta, name='user-tools-meta'),
	url(r'users/'+ username +'/tools/warn$', views.user_tools_warnings, name='user-tools-warnings'),
	url(r'users/'+ username +'/tools/ban$', views.user_tools_bans, name='user-tools-bans'),
	url(r'users/'+ username +'/block$', views.user_addblock, name='user-addblock'),
	url(r'users/'+ username +'/block_rm$', views.user_rmblock, name='user-rmblock'),
	url(r'my_blacklist$', views.user_blocklist, name='block-list'),
	# Communities
	url(r'communities.search$', views.community_search, name='community-search'),
	url(r'communities/'+ community +'$', views.community_view, name='community-view'),
	url(r'communities/favorites$', views.community_favorites, name='community-favorites'),
	url(r'communities/categories/(?P<category>[a-z]+)$', views.community_all, name='community-viewall'),
	url(r'communities/(?P<tag>[a-z]+)$', views.special_community_tag, name='special-community-tag'),
	url(r'communities/'+ community +'/favorite$', views.community_favorite_create, name='community-favorite-add'),
	url(r'communities/'+ community +'/favorite_rm$', views.community_favorite_rm, name='community-favorite-rm'),
	url(r'communities/'+ community +'/posts$', views.post_create, name='post-create'),
	url(r'communities/'+ community +'/tools$', views.community_tools, name='community-tools'),
	url(r'communities/'+ community +'/tools/set$', views.community_tools_set, name='community-tools-set'),
	url(r'c/create$', views.community_create, name='community-create'),
	url(r'c/create/do$', views.community_create_action, name='community-create-action'),
	# Posts and comments
	# Some of these NAMES (not patterns) are hardcoded into models.py
	url(r'posts/'+ post +'$', views.post_view, name='post-view'),
	url(r'posts/'+ post +'/yeah$', views.post_add_yeah, name='post-add-yeah'),
	url(r'posts/'+ post +'/yeahu$', views.post_delete_yeah, name='post-delete-yeah'),
	url(r'posts/'+ post +'/comments$', views.post_comments, name='post-comments'),
	url(r'posts/'+ post +'/lock-comments$', views.lock_the_comments, name='lock-the-comments'),
	url(r'posts/'+ post +'/change$', views.post_change, name='post-change'),
	url(r'posts/'+ post +'/profile$', views.post_setprofile, name='post-set-profile'),
	url(r'posts/'+ post +'/profile_rm', views.post_unsetprofile, name='post-unset-profile'),
	url(r'posts/'+ post +'\.rm$', views.post_rm, name='post-rm'),
	url(r'comments/'+ comment +'$', views.comment_view, name='comment-view'),
	url(r'comments/'+ comment +'/yeah$', views.comment_add_yeah, name='comment-add-yeah'),
	url(r'comments/'+ comment +'/yeahu$', views.comment_delete_yeah, name='comment-delete-yeah'),
	url(r'comments/'+ comment +'/change$', views.comment_change, name='comment-change'),
	url(r'comments/'+ comment +'/rm$', views.comment_rm, name='comment-rm'),
	# Post-meta: polls
	url(r'poll/(?P<poll>[0-9]+)/vote$', views.poll_vote, name='poll-vote'),
	url(r'poll/(?P<poll>[0-9]+)/unvote$', views.poll_unvote, name='poll-unvote'),

	# Notifications
	url(r'alive$', views.check_notifications, name='check-notifications'),
	url(r'notifications/?$', views.notifications, name='notifications'),
	url(r'notifications/friend_requests/?$', views.friend_requests, name='friend-requests'),
	url(r'notifications/(?P<notification>'+ uuidr +'+)\.rm$', views.notification_delete, name='notification-delete'),

	# User meta + messages
	url(r'activity/?$', views.activity_feed, name='activity'),
	url(r'users.search$', views.user_search, name='user-search'),
	url(r'pref$', views.prefs, name='prefs'),
	url(r'settings/profile$', views.profile_settings, name='profile-settings'),
	url(r'messages/?$', views.messages, name='messages'),
	url(r'messages/(?P<message>[0-9]+)/rm$', views.message_rm, name='message-delete'),
	url(r'messages/'+ username +'$', views.messages_view, name='messages-view'),
	url(r'messages/'+ username +'/read$', views.messages_read, name='messages-read'),

	# Help/configuration
	url(r'lights$', views.set_lighting, name='set-lighting'),
	url(r'complaints$', views.help_complaint, name='complaints'),
	url(r'invite$', views.invites, name='invites'),
	url(r'invite/create$', views.create_invite, name='create-invite'), 
	url(r'mydata$', views.my_data, name='my-data'),
	url(r'changepassword$', views.change_password, name='change-password'),
	url(r'server$', views.server_stat, name='server-stat'),
	url(r'help/rules/?$', views.help_rules, name='help-rules'),
	url(r'help/faq/?$', views.help_faq, name='help-faq'),
	url(r'help/legal/?$', views.help_legal, name='help-legal'),
	url(r'help/contact/?$', views.help_contact, name='help-contact'),
	url(r'help/login/?$', views.help_login, name='help-login'),
	url(r'help/whatads/?$', views.whatads, name='what-ads'),
	url(r'why/?$', views.help_why, name='help-why'),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# serve static and media i think???? mighTTT???????
urlpatterns += [re_path(r'^i/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

closedverse_main/templates/closedverse_main/activity.html
{% load closedverse_user %}{% u_post_list posts next 2 %}

closedverse_main/templates/closedverse_main/block-list.html
{% extends "closedverse_main/layout.html" %}
{% load static %}{% load closedverse_user %}{% load closedverse_tags %}
{% block main-body %}
{% user_sidebar request user user.profile 0 True %}
<div class="main-column"><div class="post-list-outline">
  <h2 class="label">Blocked Users</h2>
  {% if blocks %}
	<div class="list news-list" id="friend-list-content">
	{% for block in blocks %}
		<li class="news-list-content trigger" data-href="{% url "main:user-view" block.target.username %}">
			{% user_icon_container block.target %}

		  <div class="body">
			<a href="{% url "main:user-view" block.target.username %}" class="nick-name"{% if block.target.color %}style=color:{{ block.target.color }}{% endif %}>{{ block.target.nickname }}</a><br><span class="timestamp"> {% time block.created %}</span>
			<button class="button received-request-button" type="button" dataaa="{{ block.target_id }}">Unblock</button>
		  </div>
		</li>
<div class="dialog none" data-modal-types="post-unblock" id="{{ block.target_id }}">
<div class="dialog-inner">
  <div class="window">
    <h1 class="window-title">Unblock {{ block.target.nickname }}</h1>
    <div class="window-body">
      {% user_sidebar_info block.target %}
      <form method="post" data-action="{% url "main:user-rmblock" block.target.username %}">
        <p class="window-body-content">Unblock this user?</p>
        <div class="form-buttons">
          <input type="button" class="olv-modal-close-button gray-button" value="No">
          <input type="submit" value="Yes" class="post-button black-button">
        </div>
      </form>
    </div>
  </div>
</div>
</div>
	{% endfor %}
	</div>
  {% else %}
  <div class="no-content">
<p>You have not blocked any users.</p>
</div>
  {% endif %}
</div></div>
{% endblock %}

closedverse_main/templates/closedverse_main/community_list.html
{% extends "closedverse_main/layout.html" %}
{% load closedverse_tags %}{% load closedverse_community %}{% load closedverse_user %}{% block main-body %}
<div class="community-main">
		<div id="community-eyecatch"></div>
	</div>
	<div class="community-top-sidebar">
		<form action="{% url "main:community-search" %}" class="search">
			<input maxlength="32" name="query" placeholder="Search all communities" type="text"><input title="Search" type="submit" value="q">
		</form>
		
		{% if not user.is_active and user.is_authenticated %}
		<div class="notice" style="background-color: #ff9797;border: 1px solid #ff5252;">
		<p><b>Oops</b>: You've been smacked by an admin. Better luck next time.
		<div> 
		{% if user.get_warned_reason %}
		<p>Reason: "{{ user.get_warned_reason }}"</p>
		{% endif %}
		</div>
		</div>
		{% endif %}
		
		{% if settings.memo_title and settings.memo_msg %}
				<div class="post-list-outline index-memo">
					<h2 class="label">{{ settings.memo_title }}</h2>
					<div>
					{% autoescape off %}{{ settings.memo_msg }}{% endautoescape %}
					</div>
				</div>
		{% endif %}
		
	{% if announcements and request.user.is_authenticated %}
	<a href="#communities">Skip to communities</a>
	<div class="tleft">
  	<div class="post-list-outline">
      <h2 class="label">Latest Announcements</h2>
			<div class="post-body">
	        <div class="list multi-timeline-post-list">
					{% for announcement in announcements %}
						{% profile_post announcement True %}
					{% endfor %}
	        </div>
	  	</div>
  </div>
  </div>
	{% endif %}
	{% if request.user.c_tokens > 0 %}<a class="big-button" href={% url "main:community-create" %}><span class="symbol-label">Create a community</span></a>{% endif %}
		{% if availableads %}
			<div class="adx">
				<h3>User-Generated Ad</h3>
                <p><a href="/help/whatads">What are user-generated ads?</a></p>
				<a href="{{ ad.url }}"><img src="{{ ad.imageurl.url }}"></a>
			</div>
		{% endif %}
	</div>
	<div class="community-main" id="communities">
	{% if favorites %}
		<h3 class="community-title symbol community-favorite-title">Favorite communities</h3>
		<div class="card" id="community-favorite">
		  <ul>
			{% for favorite in favorites %}
				<li class="test-favorite-community">
				  <a href="{% url "main:community-view" favorite.id %}" class="icon-container">
					<img src="{{ favorite.icon }}" class="icon">

				  </a>
				</li>
			 {% endfor %}

			<li class="read-more">
			  <a href="{% url "main:community-favorites" %}" class="favorite-community-link symbol"><span class="symbol-label">Show more</span></a>
			</li>
		  </ul>
		</div>
	{% endif %}
		{% if feature %}
			{% community_page_element feature "Featured Communities" True %}
		{% endif %}
			{% community_page_element general "General Communities" False "general" %}
			{% community_page_element game "Game Communities" False "game" %}
			{% community_page_element special "Special Communities" False "special" %}
			{% community_page_element user_communities "Popular User-Created Communities" False "usr" %}
			{% if user_communities %}<a href="{% url "main:community-viewall" "usr" %}" class="big-button">Show more</a>{% endif %}
			{% community_page_element my_communities "My Communities" %}

			{% if not feature and not game and not special and not user_communities and not my_communities %}
				<div class="post-list-outline">
				{% nocontent "There are no communities of any kind yet. You can either create one in the admin panel, or make a user-created community once you sign up." %}
				</div>
			{% endif %}
	</div>
	<div id="community-guide-footer">
		<div id="guide-menu">
			<a class="arrow-button" href="{% url "main:help-why" %}"><span>Why join?</span></a>
			<a class="arrow-button" href="{% url "main:help-rules" %}"><span>{{ brand_name }} Rules</span></a>
			{% if request.user.is_authenticated %}
			<a class="arrow-button" href="{% url "main:my-data" %}"><span>My Data</span></a>
			{% endif %}
			<a class="arrow-button" href="{% url "main:help-faq" %}"><span>Frequently Asked Questions (FAQ)</span></a>
			<a class="arrow-button" href="{% url "main:what-ads" %}"><span>What are user-generated ads?</span></a>
			{% if settings.CLOSEDVERSE_PROD %}
			<a class="arrow-button" href="{% url "main:help-contact" %}"><span>Contact information</span></a>
			{% endif %}
			<a class="arrow-button" href="https://github.com/ariankordi/closedverse"><span>Closedverse Github</span></a>
			<a class="arrow-button" href="https://github.com/Mistake35/Cedar-Django"><span>Cedar-Django Github</span></a>
		</div>
	</div>
{% endblock %}

closedverse_main/templates/closedverse_main/layout.html
{% load static %}{% load closedverse_tags %}{% block html %}{% if not request.META.HTTP_X_PJAX %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
	{% endif %}
    <title>{% if title %}{{ title }} - {{ brand_name }} {% else %}{{ brand_name }}{% endif %}</title>
    {% if not request.META.HTTP_X_PJAX %}
	<meta http-equiv="content-style-type" content="text/css">
    <meta http-equiv="content-script-type" content="text/javascript">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-title" content="{{ brand_name }}">
    <meta name="description" content="{{ brand_name }} is a Miiverse clone based on Cedar-Django. It has the familiarity of Miiverse, but with a truckload of features added.">
	<meta property="og:locale" content="en_US">
	{% if ogdata %}
		<meta property="og:title" content="{{ ogdata.title }}">
		<meta property="og:type" content="article">
		<meta property="og:url" content="{{ request.build_absolute_uri }}">
		<meta property="og:image" content="{{ ogdata.image }}">
		<meta property="og:description" content="{{ ogdata.description|truncatechars:150 }}">
		<meta property="og:site_name" content="{{ brand_name }}">
		<meta property="article:published_time" content="{{ ogdata.date }}">
	{% endif %}
	<link rel="shortcut icon" type="image/png" href="{% static "img/favicon.png" %}">
    <link rel="stylesheet" type="text/css" href="{% static "closedverse.css" %}">
	<link id="darkness" {% if request.session.lights %}disabled {% endif %}rel="stylesheet" type="text/css" href="{% static "blueness.css" %}">
	<script src="{% static "jslibs.js" %}"></script>
    <script src="{% static "closedverse.js" %}"></script>
    {% color_theme request as theme %}
		{% if theme %}<script>
  var mainColor = "{{ theme }}";
  var darkColor;
  var slightlyDarkColor;
  var darkerColor;
  var lightColor;

  function changeThemeColor() {
    // Convert hex to RGB
    var rgb = hexToRgb(mainColor);
    var mainColorR = rgb[0];
    var mainColorG = rgb[1];
    var mainColorB = rgb[2];

    // Calculate light color
    var lightColorR = mainColorR > 85 ? mainColorR * 2 : mainColorR + 175;
    lightColorR = lightColorR > 255 ? 255 : lightColorR;
    var lightColorG = mainColorG > 85 ? mainColorG * 2 : mainColorG + 175;
    lightColorG = lightColorG > 255 ? 255 : lightColorG;
    var lightColorB = mainColorB > 85 ? mainColorB * 2 : mainColorB + 175;
    lightColorB = lightColorB > 255 ? 255 : lightColorB;

    // Calculate dark colors
    darkColor = rgb2hex(mainColorR / 4, mainColorG / 4, mainColorB / 4);
    lightColor = rgb2hex(lightColorR, lightColorG, lightColorB);
    slightlyDarkColor = rgb2hex(mainColorR / 1.4, mainColorG / 1.4, mainColorB / 1.4);
    darkerButNotThatDark = rgb2hex(mainColorR / 6, mainColorG / 6, mainColorB / 6);
    darkerColor = rgb2hex(mainColorR / 8, mainColorG / 8, mainColorB / 8);

    // Set CSS variables
    document.documentElement.style.setProperty("--theme", `rgb(${mainColorR}, ${mainColorG}, ${mainColorB})`);
    document.documentElement.style.setProperty("--theme-dark", darkColor);
    document.documentElement.style.setProperty("--theme-slightly-dark", slightlyDarkColor);
    document.documentElement.style.setProperty("--theme-darker", darkerColor);
    document.documentElement.style.setProperty("--theme-a-bit-darker", darkerButNotThatDark);
    document.documentElement.style.setProperty("--theme-light", lightColor);
  }

  // hex -> rgb
  function hexToRgb(hex) {
    var bigint = parseInt(hex, 16);
    var mainColorR = (bigint >> 16) & 255;
    var mainColorG = (bigint >> 8) & 255;
    var mainColorB = bigint & 255;
    return [mainColorR, mainColorG, mainColorB];
  }

  // rgb -> hex
  function rgb2hex(red, green, blue) {
    var rgb = blue | (green << 8) | (red << 16);
    return "#" + (0x1000000 + rgb).toString(16).slice(1)
  }

  function toDefault() {
    document.documentElement.style.setProperty("--theme", "");
    document.documentElement.style.setProperty("--theme-dark", "initial");
    document.documentElement.style.setProperty("--theme-slightly-dark", "initial");
    document.documentElement.style.setProperty("--theme-darker", "initial");
    document.documentElement.style.setProperty("--theme-a-bit-darker", "initial");
    document.documentElement.style.setProperty("--theme-light", "initial");
  }

  changeThemeColor();
        </script>{% endif %}
		<style>
			:root {
			{% if request.user.bg_url %}--background: url({{ request.user.bg_url }});{% endif %}
			}
		</style>
  </head>

  <body class=""{% if request.user.is_authenticated %}
  sess-usern="{{ request.user.username }}"
  {% endif %}>
    <div id="wrapper"{% if not request.user.is_authenticated %} class="guest"{% endif %}>
      <div id="sub-body">
        <menu id="global-menu">
          <li id="global-menu-logo"><h1><a href="/"><img src="{{ brand_logo }}" alt="{{ brand_name }}"></a></h1></li>
		  {% if request.user.is_authenticated %}
		  {% invite_only request as inv %}
          <li id="global-menu-list">
            <ul>
              <li id="global-menu-mymenu"><a href="{% url "main:user-view" request.user.username %}"><span class="icon-container {% if request.user.get_class.0 %} official"><img src="{% user_class request.user %}" class="official-tag">{% else %}">{% endif %}<img src="{% avatar request.user %}" alt="User Page"></span><span>User Page</span></a></li>
			  <li id="global-menu-feed"><a href="{% url "main:activity" %}" class="symbol"><span>Activity Feed</span></a></li>
              <li id="global-menu-community"><a href="/" class="symbol"><span>Communities</span></a></li>
			  <li id="global-menu-message"><a href="{% url "main:messages" %}" class="symbol"><span>Messages</span></a></li>
			  <li id="global-menu-news"><a href="{% url "main:notifications" %}" class="symbol"></a></li>
              <li id="global-menu-my-menu"><button class="symbol js-open-global-my-menu open-global-my-menu"></button>
                <menu id="global-my-menu" class="invisible none">
                  <li><a href="{% url "main:profile-settings" %}" class="symbol my-menu-profile-setting"><span>Profile settings</span></a></li>
                  <li><a href="#" class="symbol my-menu-account-setting"><span>Account preferences</span></a></li>
                  {% if inv %}<li><a href="{% url "main:invites" %}" class="symbol my-menu-guide"><span>Invites</span></a></li>{% endif %}
                  <li><a href="{% url "main:special-community-tag" "announcements" %}" class="symbol my-menu-openman"><span>{{ brand_name }} Announcements</span></a></li>
                  <li><a href="{% url "main:special-community-tag" "changelog" %}" class="symbol my-menu-openman"><span>{{ brand_name }} Changelog</span></a></li>
                  <li><a href="{% url "main:help-faq" %}" class="symbol my-menu-guide"><span>Frequently Asked Questions (FAQ)</span></a></li>
				  <li><a href="{% url "main:help-rules" %}" class="symbol my-menu-guide"><span>{{ brand_name }} Rules</span></a></li>
				  <!-- uncomment the below if you want the feedback thing to be present -->
<!--				    <li><a href="#" class="symbol my-menu-white-power"><span>Feedback/bug report</span></a></li> -->
                  <li><a href="{% url "main:server-stat" %}" class="symbol my-menu-openman"><span>Server Statistics</span></a></li>
                  <li><a href="{% url "main:block-list" %}" class="symbol my-menu-openman"><span>My block list</span></a></li>
				  <li>
                    <form action="{% url "main:logout" %}" method="post" id="my-menu-logout" class="symbol">
                      {% csrf_token %}
                      <input type="submit" value="Log out">
                    </form>
                  </li>
                </menu>
              </li>
            </ul>
          </li>
		  {% else %}
		  <li id="global-menu-login">
            <a href="{% url "main:login" %}" class="login">
              <input type="image" alt="Sign in" src="{% static "img/sign-in.png" %}">
            </a>
          </li>
		  {% endif %}
        </menu>
      </div>
	  <div id="container">
	  {% endif %}
      <div id="main-body"
    class="{% if classes %}{{ classes|join:" " }} {% endif %}{% if not request.user.is_authenticated %}
	guest{% endif %}"
	csrf-token="{{ csrf_token }}">
	  {% block main-body %}
	  {% endblock %}
      </div>
	  {% if not request.META.HTTP_X_PJAX %}
	  </div>
	  <!--
      <div id="footer">
        <div id="footer-inner">
          <div class="link-container">
			<p><a href="/help/contact">Contact</a> <a href="/help/rules">Rules</a></p>
			<p id="copyright">Cedar Team, 2022</p>
			</div>
        </div>
		-->
      </div>
    </div>
  </body>
</html>
{% endif %}{% endblock html %}

closedverse_main/templates/closedverse_main/login_page.html
{% extends "closedverse_main/layout.html" %}
{% load static %}{% block main-body %}
<div class="main-column center">
    <div class="post-list-outline login-page">
        <form method="post">
			<img src="{{ brand_logo }}">
			<p class="lh">Log In</p>
			<p>Sign in to access {{ brand_name }}</p>
			<div class="login-box">
    			<h3 class='label'>{{ form.username }}</h3>
				<h3 class='label'>{{ form.password }}</h3>
    		</div>
			{% csrf_token %}

			<p class="red" style="margin-bottom:6px">
				{% for field, errors in form.errors.items %}
					{% for error in errors %}
						{{ error }}<br>
					{% endfor %}
				{% endfor %}
			</p>

			<button type="submit" class="button">Sign In</button>
			<div class="ll">
				{% if allow_signups %}
				<p>If you don't have an account, <a href="{% url "main:signup" %}"><b>sign up</b> here.</a></p>
				{% else %}
			    <p>Signing up is disabled for now, check back later.</p>
				{% endif %}
				{% if reset_supported %}
				<p>If you forgot your password, <a href="{% url "main:forgot-passwd" %}"><b>reset</b> it here.</a></p>
				{% endif %}
				<br><p>If you need help with logging in, see the <a href="{% url "main:help-login" %}"><b>login help</b></a> page.</p>
			</div>
		</form>
	</div>
</div>
{% endblock %}

closedverse_main/templates/closedverse_main/messages.html
{% extends "closedverse_main/layout.html" %}
{% load static %}{% load closedverse_tags %}{% load closedverse_user %}
{% block main-body %}
{% user_sidebar request user user.profile 0 True %}
<div class="main-column messages">
  <div class="post-list-outline">

    <h2 class="label">Messages
		<span class="message-chk">
			<input type="checkbox" name="online" value="{% if request.session.messages_online %}n{% else %}1{% endif %}"{% if request.session.messages_online %} checked{% endif %}> Only show online friends
		</span>
	</h2>
	<!--
	{% if friends %}
		<form class="friend-search search" action="{% url "main:messages" %}">
			<input type="text" name="query" title="Search friends" placeholder="Search friends" minlength="2" maxlength="16">
			<input type="submit" value="q" title="Search">
		</form>
	{% endif %}
	-->
	<div class="list">
		{% if friends %}
				<ul class="list-content-with-icon-and-text arrow-list" data-next-page-url="{% if next %}?offset={{ next }}{% endif %}">
		{% for friend in friends %}
					<li class="trigger{% if not friend.get_latest_msg.mine and friend.get_latest_msg.read == False %} notify{% endif %}" data-href="{% url "main:messages-view" friend.username %}">
						{% user_icon_container friend 0 True %}

					  <div class="body">
						<p class="title">
						  <span class="nick-name"><a {% if friend.color %}style=color:{{ friend.color }}{% endif %} href="{% url "main:user-view" friend.username %}">{{ friend.nickname }}</a></span>
						  <span class="id-name">{{ friend.username }}</span>
						</p>
						{% if friend.get_latest_msg %}
						<span class="timestamp">{% time friend.get_latest_msg.created %}</span>
						<p class="text {% if friend.get_latest_msg.is_rm %}type-memo {% endif %}{% if friend.get_latest_msg.mine %}my{% else %}other{% endif %}">{{ friend.get_latest_msg.trun }}</p>
						{% else %}
						<p class="text placeholder">You haven't exchanged messages with this user yet.</p>
						{% endif %}

					  </div>
					</li>
		{% endfor %}
			</ul>
	{% else %}
		{% nocontent "You don't have any friends yet." %}
	{% endif %}
	</div>
  </div>
</div>
{% endblock %}

closedverse_main/templates/closedverse_main/signups-blocked.html
{% extends "closedverse_main/layout.html" %}
{% load closedverse_tags %}{% block main-body %}
{% nocontent "Sign ups are disabled for now. Please contact the administrator using the contact page." %}
{% endblock %}